:version: 0.1.0

= Client Dependencies Gradle Plugin

The Gradle plugin allows you to declare client side dependencies in *build.gradle* from bower, npm or git and
with a much clearer dependencies resolution model.

== Getting Started

[source,gradle,subs='attributes']
----
plugins {
    id 'com.craigburke.client-dependencies' version '{version}'
}
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description*

| clientInstall | Installs all the client dependencies you have set in your build.gradle

| clientRefresh | Refreshes client dependencies (if you add or modify your configuration)

| clientClean | Removes client dependencies and clears the cache

|===

== Declaring dependencies

You can specify dependencies from different sources (npm, bower or git) and control which files are included in your project by using the DSL shown below.

[source,gradle,subs='attributes']
----
plugins {
    id 'com.craigburke.client-dependnencies' version '{version}'
}

clientDependencies {
    bower {
        'jquery'('2.0.0') // <1>
    }

    npm {
        'bootstrap'('3.3.6', exclude:'jquery') // <2>
        'restangular'('1.5.0', transitive: false) // <3>
        'animate.css'('1.0.0', url: 'https://github.com/daneden/animate.css.git')
    }
}
----
<1> Installs jquery from bower and into the location (`src/assets/vendor/jquery`) using the default copy settings
<2> Installs bootstrap from npm and excludes the dependency `jquery`
<4> Installs restangular from npm but doesn't include any child dependencies
<4> Use the url property to use a git repo as a dependency source

== Overriding the copy task

By passing a closure as the last argument you have full control of what files get copied and where they get copied to.
See: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html[Gradle Copy]


For example:
[source,gradle,subs='attributes']
----
clientDependencies {
    npm {
        'bootstrap'('3.3.6') {
            include 'dist/**'
            exclude '**/*.min.*', '**/*.map', '**/npm.js'
            eachFile { it.path -= 'dist/' }
        }
    }
}
----
